### ISSUE TITLE
App crashes when you change tabs and interact with the start/stop button

### ISSUE THREAD

**Issue by heytherewill** [toggl/android#354]
## Description
If you press any tab and then try to interact with the start/stop button, the app crashes. The tap itself is still registered, though.

## Definition of done
- [ ] The app no longer crashes when you switch tabs and interact with the start/stop button.

**Comment by pdrj** [comment]
```
2020-05-29 14:43:59.169 29136-29136/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.toggl.aurora.debug, PID: 29136
    java.lang.IllegalStateException: running_time_entry_description must not be null
        at com.toggl.timer.running.ui.RunningTimeEntryFragment.updateRunningTimeEntryCard(RunningTimeEntryFragment.kt:73)
        at com.toggl.timer.running.ui.RunningTimeEntryFragment.access$updateRunningTimeEntryCard(RunningTimeEntryFragment.kt:28)
        at com.toggl.timer.running.ui.RunningTimeEntryFragment$onViewCreated$2$1.invokeSuspend(RunningTimeEntryFragment.kt:61)
        at com.toggl.timer.running.ui.RunningTimeEntryFragment$onViewCreated$2$1.invoke(Unknown Source:10)
        at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Collect.kt:138)
        at kotlinx.coroutines.flow.FlowKt__TransformKt$filterNotNull$$inlined$unsafeTransform$1$2.emit(Collect.kt:138)
        at kotlinx.coroutines.flow.FlowKt__DistinctKt$distinctUntilChangedBy$$inlined$distinctUntilChangedBy$FlowKt__DistinctKt$1$2.emit(Collect.kt:141)
        at com.toggl.timer.running.ui.RunningTimeEntryFragment$onViewCreated$2$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:139)
        at kotlinx.coroutines.flow.FlowKt__DistinctKt$distinctUntilChangedBy$$inlined$distinctUntilChangedBy$FlowKt__DistinctKt$1$2.emit(Collect.kt:141)
        at com.toggl.architecture.core.FlowStore$view$$inlined$map$1$2.emit(Collect.kt:139)
        at kotlinx.coroutines.flow.FlowKt__DistinctKt$distinctUntilChangedBy$$inlined$distinctUntilChangedBy$FlowKt__DistinctKt$1$2.emit(Collect.kt:141)
        at com.toggl.architecture.core.FlowStore$view$$inlined$map$1$2.emit(Collect.kt:139)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:59)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:11)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:175)
        at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:137)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:108)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:306)
        at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:393)
        at kotlinx.coroutines.channels.AbstractChannel$ReceiveElement.completeResumeReceive(AbstractChannel.kt:888)
        at kotlinx.coroutines.channels.ConflatedChannel.offerInternal(ConflatedChannel.kt:62)
        at kotlinx.coroutines.channels.ConflatedBroadcastChannel$Subscriber.offerInternal(ConflatedBroadcastChannel.kt:295)
        at kotlinx.coroutines.channels.ConflatedBroadcastChannel.offerInternal(ConflatedBroadcastChannel.kt:257)
        at kotlinx.coroutines.channels.ConflatedBroadcastChannel.send(ConflatedBroadcastChannel.kt:229)
        at com.toggl.architecture.core.FlowStore$Companion$create$2$1.invokeSuspend(Store.kt:71)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by heytherewill** [comment]
This doesn't seem to be a problem anymore
