### ISSUE TITLE
Fix Calendar bugs, crashes & inconsistencies

### ISSUE THREAD

**Issue by daividssilverio** [toggl/android#502]
## Description
While developing the calendar widget & contextual menu views, I found these bugs/crashes/inconsistencies:

1. CalendarContextualMenu bugs
    1. for all time entries:
        - Edit: We are navigating to the Timer Fragment...
    
    2. when handling a stopped time entry
        When picking actions:
        - Save: has no effect
        - Continue: crash with:
            ```
            java.lang.IllegalStateException: running_time_entry_description must not be null
            at com.toggl.timer.running.ui.RunningTimeEntryFragment.updateRunningTimeEntryCard(RunningTimeEntryFragment.kt:73)
            ```
    
    3. when handling a running time entry:
        - Discard: has no effect
        - Save (after dragging the start time): crash with:
            ```
            com.toggl.common.feature.timeentry.exceptions.TimeEntryShouldNotBeRunningException: Action cannot be performed on a running time entry
            at com.toggl.common.feature.timeentry.extensions.EditableTimeEntryExtensionsKt.throwIfRunning(EditableTimeEntryExtensions.kt:33)
            at com.toggl.calendar.contextualmenu.domain.ContextualMenuReducer.reduce(ContextualMenuReducer.kt:51)
            ```

2. CalendarDay bugs
    1. Do something in the calendar view
    2. Navigate to the timer
    3. Go back to the calendar view and select some calendar item
    4. :boom: with:
        ```
        java.lang.NullPointerException: Attempt to invoke virtual method 'void com.toggl.calendar.calendarday.ui.views.CalendarWidgetView.updateList(java.util.List)' on a null object reference
        at com.toggl.calendar.calendarday.ui.CalendarDayFragment$onViewCreated$1.invokeSuspend(CalendarDayFragment.kt:52)
        ```

## Dependencies
#499 

## Definition of done
- [ ] All of the above is fixed (feel free to create smaller issues if necessary)

**Comment by sofokli1** [comment]
Apart from the above crashes. Tapping outside of the CTMenu does not dismiss it.
